### ISSUE TITLE
Test failure on latest bom

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Websocket-Jetty#5]
Currently seeing this stack trace when running tests (after applying #4):
```
java.lang.UnsupportedOperationException`
	at net.openhft.chronicle.websocket.jetty.JettyDocumentContext.index(JettyDocumentContext.java:46)
	at net.openhft.chronicle.wire.MethodReader.readOne(MethodReader.java:224)
	at net.openhft.chronicle.websocket.jetty.JettyWebSocketServiceAdapter.onWebSocketText(JettyWebSocketServiceAdapter.java:71)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:375)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.607 sec <<< FAILURE! - in net.openhft.chronicle.websocket.jetty.JettyWebSocketServerTest
registersServletsWithDifferentNames(net.openhft.chronicle.websocket.jetty.JettyWebSocketServerTest)  Time elapsed: 1.605 sec  <<< FAILURE!
java.lang.AssertionError: expected:<foo> but was:<null>
	at net.openhft.chronicle.websocket.jetty.JettyWebSocketServerTest.registersServletsWithDifferentNames(JettyWebSocketServerTest.java:38)
```

**Comment by peter-lawrey** [comment]
Hi. Let me pick this up. Peter.

**Comment by scottkidder** [comment]
Thanks Peter https://github.com/OpenHFT/Chronicle-Websocket-Jetty/commit/71072c56568d433bfb0e1ed573c0823d0013e809
